### ISSUE TITLE
Certificates are expired for windows 10 ?

### ISSUE THREAD

**Issue by sh-git-repo** [certifi/certifi.io#25]
I have a windows 10 machine, and I am not sure what the problem is, I was able to run everything till today until a few hours back but now I keep running into SSL certificate Expired error for some reason I ran the script given by urllib3 docs to check whether the certificate is valid or not.
```
import certifi
import urllib3

http = urllib3.PoolManager(
    cert_reqs="CERT_REQUIRED",
    ca_certs=certifi.where()
)

http.request("GET", "https://httpbin.org/")
# (No exception)

http.request("GET", "https://expired.badssl.com")
```

Below are the results
```
Traceback (most recent call last):
  File "d:\exirio-backend\work_venv\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "d:\exirio-backend\work_venv\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "d:\exirio-backend\work_venv\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "d:\exirio-backend\work_venv\lib\site-packages\urllib3\connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "d:\exirio-backend\work_venv\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "d:\exirio-backend\work_venv\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\khans\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\khans\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\khans\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\exirio-backend\csvs\test.py", line 12, in <module>
    http.request("GET", "https://expired.badssl.com")
  File "d:\exirio-backend\work_venv\lib\site-packages\urllib3\request.py", line 74, in request
    return self.request_encode_url(
  File "d:\exirio-backend\work_venv\lib\site-packages\urllib3\request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "d:\exirio-backend\work_venv\lib\site-packages\urllib3\poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "d:\exirio-backend\work_venv\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "d:\exirio-backend\work_venv\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "d:\exirio-backend\work_venv\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "d:\exirio-backend\work_venv\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "d:\exirio-backend\work_venv\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='expired.badssl.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))
```
I tried removing and reinstalling python and reinstalling the libraries as noted in the docs but nothing seems to help.

**Comment by sigmavirus24** [comment]
To be clear to folks finding this later `host='expired.badssl.com'` provides a certificate that's expired always to test cases like this explicitly. This is not a bug nor a place to ask for help with some server's expired TLS certificate

**Comment by sh-git-repo** [comment]
@sigmavirus24, I am very sorry for opening the issue here, actually the issue seems to be that some root certificates in the windows OS have expired on 30th September.

**Comment by sigmavirus24** [comment]
> @sigmavirus24, I am very sorry for opening the issue here, actually the issue seems to be that some root certificates in the windows OS have expired on 30th September.

Your original traceback has `HTTPSConnectionPool(host='expired.badssl.com', port=443` at the very end. Based on what's here, the error you provided is expected
